# Generated by Django 5.2.7 on 2025-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_drfpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
