# Generated by Django 5.2.7 on 2025-10-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_dosen', to='accounts.profile')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_mahasiswa', to='accounts.profile')),
            ],
        ),
    ]
